version: '3.8'

services:
    web:
        build: .
        command: >
            sh -c  "python manage.py migrate &&
                    python /src/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/src
        ports:
            - 8000:8000 
        depends_on:
            - db
        env_file:
            - fp.dev.env
        environment:
            - "DJANGO_DEBUG=True"
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
    postgres_data:

