# Generated by Django 3.0.7 on 2020-10-14 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
